FROM python:3.14

RUN apt-get update

COPY . /postgres_python

WORKDIR /postgres_python
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


CMD ["python", "postgres.py"]